name: CI Implementation for the project

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - k8s_aws_eks/readme.txt
      - go-web-app-helm/values.yaml

jobs:

  build:

    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.5'

      - name: Download dependencies
        run: go mod download

      - name: Build application
        run: go build -o go-web-app-binary

      - name: Run unit tests
        run: go test ./...

  code-quality:

    name: Code Quality (Linting)
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.5'

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.56.2
          args: --timeout=5m

  docker-build:

    if: github.event_name == 'push'
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    needs: code-quality

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract commit SHA
        id: vars
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ci-go-web-image:${{ steps.vars.outputs.IMAGE_TAG }}

  # update-helm-values:
  
  #   if: github.event_name == 'push'
  #   name: Update Helm image tag
  #   runs-on: ubuntu-latest

  #   needs: docker-build

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4
  #       with:
  #         token: ${{ secrets.GITHUB_TOKEN }}

  #     - name: Update image tag in Helm values.yaml
  #       run: |
  #         sed -i 's/tag:.*/tag: "'${GITHUB_SHA::7}'"/' go-web-app-helm/values.yaml

  #     - name: Commit and push changes
  #       run: |
  #         git config user.name "github-actions"
  #         git config user.email "github-actions@github.com"
  #         git add go-web-app-helm/values.yaml
  #         git commit -m "chore(helm): update image tag to ${GITHUB_SHA::7}"
  #         git push
